FROM postgres:17-bookworm

COPY docker/postgres/pg_hba.prod.conf /etc/postgresql/pg_hba.conf
COPY docker/postgres/entrypoint.sh /usr/local/bin/finsight-postgres-entrypoint.sh
COPY docker/postgres/init/ /docker-entrypoint-initdb.d/
RUN chmod 0755 /usr/local/bin/finsight-postgres-entrypoint.sh /docker-entrypoint-initdb.d/*.sh

ENTRYPOINT ["/usr/local/bin/finsight-postgres-entrypoint.sh"]
CMD ["postgres", "-c", "hba_file=/etc/postgresql/pg_hba.conf", "-c", "ssl=on", "-c", "ssl_cert_file=/run/finsight-postgres/server.crt", "-c", "ssl_key_file=/run/finsight-postgres/server.key", "-c", "ssl_min_protocol_version=TLSv1.2", "-c", "password_encryption=scram-sha-256"]
