package com.app.sme_health_backend.audit.model;

public enum AuditEventType {
    // Authentication
    AUTH_LOGIN_SUCCESS,
    AUTH_LOGIN_FAILURE,
    AUTH_LOGOUT,
    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    SESSION_REVOKED,
    MFA_CHALLENGE_SUCCESS,
    MFA_CHALLENGE_FAILURE,
    MFA_ENABLED,
    MFA_DISABLED,
    RECOVERY_CODE_USED,

    // Membership / Authorization
    BUSINESS_CREATED,
    MEMBERSHIP_CREATED,
    MEMBERSHIP_ROLE_CHANGED,
    MEMBERSHIP_SUSPENDED,
    MEMBERSHIP_REACTIVATED,
    ACTIVE_BUSINESS_CHANGED,

    // Financial / Data Mutations
    MONTHLY_RECORD_CREATED,
    MONTHLY_RECORD_UPDATED,
    MONTHLY_RECORD_DELETED,
    DOCUMENT_UPLOADED,
    DOCUMENT_CONFIRMED,
    DOCUMENT_CORRECTED,
    DOCUMENT_DELETED,

    // Integration / Background
    WHATSAPP_SENT,
    WHATSAPP_FAILED,
    OCR_PROCESSING_FAILED,
    CRYPTO_MIGRATION_EXECUTED,
    CRYPTO_KEY_ROTATION_EXECUTED,

    // Platform Administration
    PLATFORM_ADMIN_GRANTED,
    PLATFORM_ADMIN_REVOKED,
    PLATFORM_ADMIN_MFA_RESET,
    PLATFORM_ADMIN_ACTION
}
