spring.application.name=sme-health-backend

spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:sme_health}
spring.datasource.username=${POSTGRES_USER:sme_user}
spring.datasource.password=${POSTGRES_PASSWORD:sme_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect